services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    command: air api/main.go -b 0.0.0.0
    networks:
      - appnet
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - appnet
    depends_on:
      - backend

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: series
    ports:
      - "5433:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  postgres-db:

networks:
  appnet:
    driver: bridge
